### ISSUE TITLE
npm run start:prod报错，我发现没有dist/main,中间要加src才能执行，但是执行报下面错误

### ISSUE THREAD

**Issue by lyseky** [givebest/node-nest-vue-nuxt-cms#10]
$ node dist/src/main
[Nest] 32817  - 06/02/2023, 6:01:38 PM     LOG [NestFactory] Starting Nest application...
[Nest] 32817  - 06/02/2023, 6:01:38 PM   ERROR [ExceptionHandler] {(intermediate value)(intermediate value)(intermediate value)}[process.env.FM_SERVER_ENV] is not a function
TypeError: {(intermediate value)(intermediate value)(intermediate value)}[process.env.FM_SERVER_ENV] is not a function
    at exports.default [as metatype] (/Users/lyseky/workspace/lyseky/igxstudio/server/dist/config/config.default.js:20:29)
    at Injector.instantiateClass (/Users/lyseky/workspace/lyseky/igxstudio/server/node_modules/@nestjs/core/injector/injector.js:304:55)
    at callback (/Users/lyseky/workspace/lyseky/igxstudio/server/node_modules/@nestjs/core/injector/injector.js:48:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Injector.resolveConstructorParams (/Users/lyseky/workspace/lyseky/igxstudio/server/node_modules/@nestjs/core/injector/injector.js:124:24)
    at async Injector.loadInstance (/Users/lyseky/workspace/lyseky/igxstudio/server/node_modules/@nestjs/core/injector/injector.js:52:9)
    at async Injector.loadProvider (/Users/lyseky/workspace/lyseky/igxstudio/server/node_modules/@nestjs/core/injector/injector.js:74:9)
    at async Promise.all (index 4)
    at async InstanceLoader.createInstancesOfProviders (/Users/lyseky/workspace/lyseky/igxstudio/server/node_modules/@nestjs/core/injector/instance-loader.js:44:9)
    at async /Users/lyseky/workspace/lyseky/igxstudio/server/node_modules/@nestjs/core/injector/instance-loader.js:29:13
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Process finished with exit code 1

**Comment by givebest** [comment]
先运行下：`npm run build` 试下

**Comment by lyseky** [comment]
# lyseky @ m920x in ~ [17:48:21]
$ node -v
v18.13.0

# lyseky @ m920x in ~ [8:25:57]
$ npm -v
8.19.3

> 先运行下：`npm run build` 试下

执行过了npm run build，然后npm run start:prod,一样报上面错误

**Comment by lyseky** [comment]
我自己重写了config.default.ts解决了
