### ISSUE TITLE
ERROR [TypeOrmModule] Unable to connect to the database

### ISSUE THREAD

**Issue by idefa** [givebest/node-nest-vue-nuxt-cms#5]
[Nest] 227  - 07/07/2022, 8:56:04 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (4)...
QueryFailedError: Duplicate entry '' for key 'PRIMARY'
    at QueryFailedError.TypeORMError [as constructor] (/app/src/error/TypeORMError.ts:7:9)
    at new QueryFailedError (/app/src/error/QueryFailedError.ts:9:9)
    at Query.onResult (/app/src/driver/mysql/MysqlQueryRunner.ts:196:37)
    at Query.execute (/app/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/app/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/app/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (/app/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/app/node_modules/mysql2/lib/connection.js:92:25)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:309:12)
[Nest] 227  - 07/07/2022, 8:56:07 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (5)...
QueryFailedError: Duplicate entry '' for key 'PRIMARY'
    at QueryFailedError.TypeORMError [as constructor] (/app/src/error/TypeORMError.ts:7:9)
    at new QueryFailedError (/app/src/error/QueryFailedError.ts:9:9)
    at Query.onResult (/app/src/driver/mysql/MysqlQueryRunner.ts:196:37)
    at Query.execute (/app/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/app/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/app/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (/app/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/app/node_modules/mysql2/lib/connection.js:92:25)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:309:12)

**Comment by givebest** [comment]
https://github.com/givebest/node-nest-vue-nuxt-cms/commit/43bd4a68dac01cb0ee4ac5e06997592b981f5a25
